### PR TITLE
smtp password creation and domain

### LINKED ISSUE #5: Can't launch decidim - message_encryptor openssl::cipher error
Hello, first of all, thanks a lot for this repo, it looks promising and should help with docker deployment of decidim !

I cloned your repo and built my own image (didn't change anything in your files). Build went ok, but once docker runs decidim container, it is stuck on this error : 
```
/usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/message_encryptor.rb:201:in `final': OpenSSL::Cipher::CipherError
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/message_encryptor.rb:201:in `_decrypt`
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/message_encryptor.rb:157:in `decrypt_and_verify`
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/messages/rotator.rb:21:in `decrypt_and_verify`
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/encrypted_file.rb:79:in `decrypt`
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/encrypted_file.rb:42:in `read`
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/encrypted_configuration.rb:21:in `read`
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/encrypted_configuration.rb:33:in `config`
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/encrypted_configuration.rb:38:in `options`
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/core_ext/module/delegation.rb:271:in `method_missing`
	from /usr/local/bundle/ruby/2.6.0/gems/devise-4.7.3/lib/devise/secret_key_finder.rb:24:in `key_exists?`
	from /usr/local/bundle/ruby/2.6.0/gems/devise-4.7.3/lib/devise/secret_key_finder.rb:10:in `find`
	from /usr/local/bundle/ruby/2.6.0/gems/devise-4.7.3/lib/devise/rails.rb:37:in `block in <class:Engine>`
	from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:32:in `instance_exec`
	from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:32:in `run`
	from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:61:in `block in run_initializers`
	from /usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each`
	from /usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component`
	from /usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from`
	from /usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component`
	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each`
	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call`
	from /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component`
	from /usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each`
	from /usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each`
	from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/initializable.rb:60:in `run_initializers`
	from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/application.rb:361:in `initialize!`
	from /decidim-app/config/environment.rb:5:in `<main>`
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require`
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi`
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register`
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi`
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require`
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require`
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency`
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require`
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative`
	from config.ru:3:in `block in <main>`
	from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval`
	from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string`
	from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file`
	from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file`
	from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:349:in `build_app_and_options_from_config`
	from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:249:in `app`
	from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/commands/server/server_command.rb:27:in `app`
	from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:422:in `wrapped_app`
	from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:312:in `block in start`
	from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:379:in `handle_profiling`
	from /usr/local/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:311:in `start`
	from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/commands/server/server_command.rb:53:in `start`
	from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/commands/server/server_command.rb:147:in `block in perform`
	from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/commands/server/server_command.rb:142:in `tap`
	from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/commands/server/server_command.rb:142:in `perform`
	from /usr/local/bundle/ruby/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run`
	from /usr/local/bundle/ruby/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command`
	from /usr/local/bundle/ruby/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch`
	from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/command/base.rb:69:in `perform`
	from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/command.rb:46:in `invoke`
	from /usr/local/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/commands.rb:18:in `<main>`
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require`
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi`
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register`
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi`
	from /usr/local/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require`
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require`
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency`
	from /usr/local/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require`
	from bin/rails:4:in `<main>`
Exiting
```

Any help would be greatly appreciated :)

### PR DESCRIPTION
**Pull request by raulsperoni**
Hi, some suggestions:

- Fixing Postgres version in docker-compose to avoid a mess when you have previous versions installed.
- For some reason redirection for organizations is not woking with a port different than 80 in localhost.
- I've found that SECRET_KEY_BASE is needed for the encryption of passwords. Particularly SMTP password in organization creation.
- Also without some value in SMTP_DOMAIN, SMTP won't work.

And I had to comment out RAILS_MASTER_KEY to fix #5

### CODE REVIEW

**Comment by larueli** [comment]
Hello !

Thank you very much for your contribution !

* I'm ok for fixing postgres version, it's a good practise !
* I don't understand why are you changing the port on the host side, it should work whatever port is chosen, and it's best to use unprivileged ports. You had some trouble with it ? I never tried decidim with multiple organizations.
* Thanks a lot ! I'm always confused with those two values (`RAILS_MASTER_KEY` and `SECRET_KEY_BASE`), thanks for you correction !
* Thanks for your correction for SMTP !

Can you explain more the second point ? Thanks a lot !

**Comment by raulsperoni** [comment]
Happy to contribute, this repo has helped me a lot, so.

On the second point. I know it should work with any port but for some reason after creating an organization and setting the host, localhost:3000, Decidim will always redirect to /system thus no letting me go to homepage or /admin. I've had trouble before with that host field in new organization form. For example it won't work if you add the scheme (http, https). Maybe this is related somehow.

Can you reproduce this?

**Comment by raulsperoni** [comment]
Hi, new commits fixes #4 and brings back 3000 port to compose.

**Review by larueli — APPROVED** [review]
Thank you very much for contributing to this project, I'm ok with all your edits.

**Pull request merged**
